#!/usr/bin/env python3
import json

# Comprehensive German translations for all 702 untranslated keys
translations = {
    "appTitle": "Team Build Pro",
    "authLoginBiometricMethodFace": "Face ID",
    "authLoginBiometricMethodTouch": "Touch ID",
    "navTeam": "Team",
    "messageCenterFilterTeam": "Team",
    "notificationsFilterTeam": "Team",
    "chatTitle": "Chat",
    "chatTypingIndicator": "{name} schreibt...",
    "chatbotTitle": "KI-Coach",
    "chatbotWelcome": "Hallo! Ich bin Ihr KI-Coach. Wie kann ich Ihnen heute beim Aufbau Ihres Teams helfen?",
    "chatbotInputHint": "Fragen Sie mich alles über Teamaufbau...",
    "chatbotSuggestion1": "Wie kann ich effektiver rekrutieren?",
    "chatbotSuggestion2": "Was sind die Zulassungsvoraussetzungen?",
    "chatbotSuggestion3": "Wie funktioniert das Feeder-System?",
    "chatbotThinking": "Denke nach...",
    "companyTitle": "Unternehmensinformationen",
    "companyAboutHeading": "Über Team Build Pro",
    "companyAboutText": "Team Build Pro ist eine professionelle SaaS-Plattform für Teamaufbau und Netzwerkwachstum. Wir stellen die Tools und Technologien bereit, um Ihr professionelles Team effektiv aufzubauen und zu verwalten.",
    "companyVersionLabel": "App-Version",
    "companyContactHeading": "Kontaktieren Sie uns",
    "companyContactEmail": "support@teambuildpro.com",
    "companyContactWebsite": "www.teambuildpro.com",
    "deleteAccountTitle": "Konto löschen",
    "deleteAccountWarning": "Warnung: Diese Aktion kann nicht rückgängig gemacht werden!",
    "deleteAccountDescription": "Das Löschen Ihres Kontos entfernt dauerhaft alle Ihre Daten, einschließlich Ihres Profils, Teaminformationen und Nachrichtenverlaufs. Diese Aktion ist unwiderruflich.",
    "deleteAccountConfirmPrompt": "Um die Löschung zu bestätigen, geben Sie bitte DELETE unten ein:",
    "deleteAccountConfirmHint": "Geben Sie Ihre E-Mail-Adresse ein",
    "deleteAccountConfirmMismatch": "Bitte geben Sie DELETE genau wie angezeigt ein",
    "deleteAccountButtonDelete": "Konto löschen",
    "deleteAccountButtonCancel": "Abbrechen",
    "deleteAccountSuccessMessage": "Ihr Konto wurde gelöscht",
    "deleteAccountErrorMessage": "Fehler beim Löschen des Kontos. Bitte kontaktieren Sie den Support.",
    "editProfileTitle": "Profil bearbeiten",
    "editProfileLabelFirstName": "Vorname",
    "editProfileLabelLastName": "Nachname",
    "editProfileLabelEmail": "E-Mail",
    "editProfileLabelPhone": "Telefonnummer",
    "editProfileLabelCity": "Stadt",
    "editProfileLabelState": "Bundesland/Provinz",
    "editProfileLabelCountry": "Land",
    "editProfileLabelBio": "Bio",
    "editProfileHintBio": "Erzählen Sie Ihrem Team etwas über sich...",
    "editProfileButtonSave": "Änderungen speichern",
    "editProfileButtonCancel": "Abbrechen",
    "editProfileButtonChangePhoto": "Foto ändern",
    "editProfileSuccessMessage": "Profil erfolgreich aktualisiert!",
    "editProfileErrorMessage": "Fehler beim Aktualisieren des Profils. Bitte versuchen Sie es erneut.",
    "eligibilityTitle": "Berechtigungsstatus",
    "eligibilityCurrentStatus": "Aktueller Status",
    "eligibilityStatusQualified": "Qualifiziert!",
    "eligibilityStatusNotQualified": "Noch nicht qualifiziert",
    "eligibilityRequirementsHeading": "Anforderungen",
    "eligibilityDirectSponsorsLabel": "Direkte Sponsoren",
    "eligibilityDirectSponsorsProgress": "{current} von {required} erforderlich",
    "eligibilityTotalTeamLabel": "Gesamte Teammitglieder",
    "eligibilityTotalTeamProgress": "{current} von {required} erforderlich",
    "eligibilityProgressBar": "Fortschritt: {percent}%",
    "eligibilityNextSteps": "Nächste Schritte",
    "eligibilityNextStepsDescription": "Teilen Sie weiterhin Ihren Empfehlungslink, um Ihr Team zu vergrößern und die Anforderungen zu erfüllen!",
    "shareTitle": "Teilen",
    "shareYourLinkHeading": "Ihr Empfehlungslink",
    "shareButtonCopyLink": "Link kopieren",
    "shareLinkCopied": "Link in die Zwischenablage kopiert!",
    "shareButtonSms": "Per SMS teilen",
    "shareButtonEmail": "Per E-Mail teilen",
    "shareButtonWhatsApp": "Per WhatsApp teilen",
    "shareButtonMore": "Weitere Optionen",
    "shareMessageTemplate": "Hey! Ich baue mein Team mit Team Build Pro auf. Mach mit: {link}",
    "shareStatsHeading": "Ihre Teilungswirkung",
    "shareStatsViews": "Link-Aufrufe",
    "shareStatsSignups": "Anmeldungen",
    "shareStatsConversion": "Konversionsrate",
    "memberDetailTitle": "Mitgliederdetails",
    "memberDetailLabelName": "Name",
    "memberDetailLabelEmail": "E-Mail",
    "memberDetailLabelPhone": "Telefon",
    "memberDetailLabelLocation": "Standort",
    "memberDetailLabelJoined": "Beigetreten",
    "memberDetailLabelSponsor": "Sponsor",
    "memberDetailLabelLevel": "Ebene",
    "memberDetailTeamStats": "Teamstatistiken",
    "memberDetailDirectSponsors": "Direkte Sponsoren: {count}",
    "memberDetailTotalTeam": "Gesamtes Team: {count}",
    "memberDetailButtonMessage": "Nachricht senden",
    "memberDetailButtonViewTeam": "Ihr Team anzeigen",
    "messageThreadTitle": "Nachrichten",
    "messageThreadInputHint": "Geben Sie Ihre Nachricht ein...",
    "messageThreadButtonSend": "Senden",
    "messageThreadEmptyState": "Noch keine Nachrichten. Starten Sie das Gespräch!",
    "messageThreadDelivered": "Zugestellt",
    "messageThreadRead": "Gelesen",
    "messageThreadSending": "Wird gesendet...",
    "messageThreadFailed": "Senden fehlgeschlagen",
    "loginTitle": "Anmelden",
    "loginButtonGoogle": "Mit Google fortfahren",
    "loginButtonApple": "Mit Apple fortfahren",
    "loginDivider": "oder",
    "loginForgotPassword": "Passwort vergessen?",
    "loginResetPasswordTitle": "Passwort zurücksetzen",
    "loginResetPasswordDescription": "Geben Sie Ihre E-Mail-Adresse ein und wir senden Ihnen einen Link zum Zurücksetzen Ihres Passworts.",
    "loginResetPasswordButtonSend": "Zurücksetzungslink senden",
    "loginResetPasswordSuccess": "Zurücksetzungslink gesendet! Überprüfen Sie Ihre E-Mails.",
    "loginResetPasswordError": "Fehler beim Senden des Zurücksetzungslinks. Bitte versuchen Sie es erneut.",
    "signupTitle": "Konto erstellen",
    "signupButtonGoogle": "Mit Google anmelden",
    "signupButtonApple": "Mit Apple anmelden",
    "signupDivider": "oder",
    "signupLabelFirstName": "Vorname",
    "signupLabelLastName": "Nachname",
    "signupLabelEmail": "E-Mail",
    "signupLabelPassword": "Passwort",
    "signupLabelConfirmPassword": "Passwort bestätigen",
    "signupLabelReferralCode": "Empfehlungscode (optional)",
    "signupButtonCreate": "Konto erstellen",
    "signupAlreadyHaveAccount": "Haben Sie bereits ein Konto?",
    "signupButtonLogin": "Anmelden",
    "signupPasswordsDontMatch": "Passwörter stimmen nicht überein",
    "signupErrorMessage": "Fehler beim Erstellen des Kontos. Bitte versuchen Sie es erneut.",
    "signupSuccessMessage": "Konto erfolgreich erstellt!",
    "profileTitle": "Profil",
    "profileButtonEdit": "Profil bearbeiten",
    "profileButtonShare": "Profil teilen",
    "profileJoinedLabel": "Beigetreten",
    "profileLocationLabel": "Standort",
    "profileSponsorLabel": "Sponsor",
    "profileStatsHeading": "Statistiken",
    "profileStatDirectSponsors": "Direkte Sponsoren",
    "profileStatTotalTeam": "Gesamtes Team",
    "profileStatEligibilityStatus": "Berechtigungsstatus",
    "profileButtonSettings": "Einstellungen",
    "profileButtonLogout": "Abmelden",
    "settingsTitle": "Einstellungen",
    "settingsAccountHeading": "Konto",
    "settingsButtonEditProfile": "Profil bearbeiten",
    "settingsButtonChangePassword": "Passwort ändern",
    "settingsButtonBiometric": "Biometrische Authentifizierung",
    "settingsNotificationsHeading": "Benachrichtigungen",
    "settingsTogglePushNotifications": "Push-Benachrichtigungen",
    "settingsToggleEmailNotifications": "E-Mail-Benachrichtigungen",
    "settingsToggleTeamGrowth": "Teamwachstum",
    "settingsToggleMilestones": "Meilensteine",
    "settingsToggleMessages": "Nachrichten",
    "settingsPrivacyHeading": "Datenschutz & Rechtliches",
    "settingsButtonPrivacyPolicy": "Datenschutzerklärung",
    "settingsButtonTermsOfService": "Nutzungsbedingungen",
    "settingsButtonDeleteAccount": "Konto löschen",
    "settingsAboutHeading": "Über",
    "settingsButtonCompanyInfo": "Unternehmensinformationen",
    "settingsButtonHelp": "Hilfe & Support",
    "settingsVersionLabel": "Version",
    "teamTitle": "Mein Team",
    "teamFilterAll": "Alle",
    "teamFilterDirect": "Direkte Sponsoren",
    "teamFilterLevel1": "Ebene 1",
    "teamFilterLevel2": "Ebene 2",
    "teamFilterLevel3": "Ebene 3+",
    "teamSearchHint": "Teammitglied suchen...",
    "teamEmptyState": "Noch keine Teammitglieder. Teilen Sie Ihren Link, um zu beginnen!",
    "teamMemberCount": "{count} Mitglieder",
    "teamSortBy": "Sortieren nach:",
    "teamSortNewest": "Neueste",
    "teamSortOldest": "Älteste",
    "teamSortName": "Name",
    "teamSortTeamSize": "Teamgröße",
    "notificationsTitle": "Benachrichtigungen",
    "notificationsFilterAll": "Alle",
    "notificationsFilterMilestones": "Meilensteine",
    "notificationsFilterMessages": "Nachrichten",
    "notificationsFilterSystem": "System",
    "notificationsEmptyState": "Keine Benachrichtigungen",
    "notificationsMarkAllRead": "Alle als gelesen markieren",
    "notificationTypeNewMember": "Neues Teammitglied",
    "notificationTypeMilestone": "Meilenstein erreicht",
    "notificationTypeMessage": "Neue Nachricht",
    "notificationTypeSystem": "Systembenachrichtigung",
    "messageCenterTitle": "Nachrichten",
    "messageCenterFilterAll": "Alle",
    "messageCenterFilterUnread": "Ungelesen",
    "messageCenterSearchHint": "Nachrichten durchsuchen...",
    "messageCenterEmptyState": "Keine Nachrichten",
    "messageCenterNewConversation": "Neue Unterhaltung",
    "dashboardTitle": "Dashboard",
    "dashboardWelcome": "Willkommen zurück, {name}!",
    "dashboardStatsHeading": "Ihre Statistiken",
    "dashboardStatDirectSponsors": "Direkte Sponsoren",
    "dashboardStatTotalTeam": "Gesamtes Team",
    "dashboardStatEligibility": "Berechtigung",
    "dashboardRecentActivityHeading": "Kürzliche Aktivität",
    "dashboardRecentActivityEmpty": "Keine kürzliche Aktivität",
    "dashboardQuickActionsHeading": "Schnellaktionen",
    "dashboardButtonShare": "Link teilen",
    "dashboardButtonViewTeam": "Team anzeigen",
    "dashboardButtonMessages": "Nachrichten",
    "dashboardButtonSettings": "Einstellungen",
    "dashboardTeamGrowthHeading": "Teamwachstum",
    "dashboardTeamGrowthToday": "Heute",
    "dashboardTeamGrowthWeek": "Diese Woche",
    "dashboardTeamGrowthMonth": "Diesen Monat",
    "dashboardTeamGrowthTotal": "Gesamt",
    "networkTitle": "Netzwerk",
    "networkFilterAll": "Alle Ebenen",
    "networkFilterDirect": "Nur Direkte",
    "networkSearchHint": "Netzwerk durchsuchen...",
    "networkEmptyState": "Noch kein Netzwerk aufgebaut",
    "networkViewTree": "Baumansicht",
    "networkViewList": "Listenansicht",
    "networkExpandAll": "Alle erweitern",
    "networkCollapseAll": "Alle reduzieren",
    "networkMemberLevel": "Ebene {level}",
    "networkMemberTeamSize": "Team: {size}",
    "analyticsTitle": "Analysen",
    "analyticsOverviewHeading": "Übersicht",
    "analyticsTimeframeDay": "Tag",
    "analyticsTimeframeWeek": "Woche",
    "analyticsTimeframeMonth": "Monat",
    "analyticsTimeframeYear": "Jahr",
    "analyticsTimeframeAll": "Alle Zeiten",
    "analyticsStatNewMembers": "Neue Mitglieder",
    "analyticsStatGrowthRate": "Wachstumsrate",
    "analyticsStatRetention": "Bindungsrate",
    "analyticsStatEngagement": "Engagement",
    "analyticsChartTeamGrowth": "Teamwachstum im Zeitverlauf",
    "analyticsChartLevelDistribution": "Ebenenverteilung",
    "analyticsChartGeography": "Geografische Verteilung",
    "analyticsExportData": "Daten exportieren",
    "trainingTitle": "Schulung",
    "trainingCategoriesHeading": "Kategorien",
    "trainingCategoryGettingStarted": "Erste Schritte",
    "trainingCategoryRecruitment": "Rekrutierung",
    "trainingCategoryLeadership": "Führung",
    "trainingCategoryAdvanced": "Fortgeschritten",
    "trainingSearchHint": "Schulungen durchsuchen...",
    "trainingEmptyState": "Keine Schulungsmaterialien verfügbar",
    "trainingModuleCompleted": "Abgeschlossen",
    "trainingModuleInProgress": "In Bearbeitung",
    "trainingModuleNotStarted": "Nicht gestartet",
    "trainingStartModule": "Modul starten",
    "trainingContinueModule": "Fortsetzen",
    "trainingMarkComplete": "Als abgeschlossen markieren",
    "resourcesTitle": "Ressourcen",
    "resourcesCategoriesHeading": "Kategorien",
    "resourcesCategoryDocuments": "Dokumente",
    "resourcesCategoryVideos": "Videos",
    "resourcesCategoryTemplates": "Vorlagen",
    "resourcesCategoryTools": "Tools",
    "resourcesSearchHint": "Ressourcen durchsuchen...",
    "resourcesEmptyState": "Keine Ressourcen verfügbar",
    "resourcesButtonDownload": "Herunterladen",
    "resourcesButtonShare": "Teilen",
    "resourcesButtonPreview": "Vorschau",
    "eventsTitle": "Veranstaltungen",
    "eventsUpcomingHeading": "Bevorstehende Veranstaltungen",
    "eventsPastHeading": "Vergangene Veranstaltungen",
    "eventsEmptyState": "Keine Veranstaltungen geplant",
    "eventsButtonRegister": "Registrieren",
    "eventsButtonCancelRegistration": "Registrierung stornieren",
    "eventsButtonAddToCalendar": "Zum Kalender hinzufügen",
    "eventsRegistrationSuccess": "Erfolgreich registriert!",
    "eventsRegistrationError": "Fehler bei der Registrierung. Bitte versuchen Sie es erneut.",
    "eventDetailsTitle": "Veranstaltungsdetails",
    "eventDetailsDateLabel": "Datum",
    "eventDetailsTimeLabel": "Uhrzeit",
    "eventDetailsLocationLabel": "Standort",
    "eventDetailsDescriptionLabel": "Beschreibung",
    "eventDetailsAttendeesLabel": "Teilnehmer",
    "eventDetailsOrganizerLabel": "Veranstalter",
    "goalsTitle": "Ziele",
    "goalsActiveHeading": "Aktive Ziele",
    "goalsCompletedHeading": "Abgeschlossene Ziele",
    "goalsEmptyState": "Noch keine Ziele festgelegt",
    "goalsButtonCreateNew": "Neues Ziel erstellen",
    "goalsButtonEdit": "Bearbeiten",
    "goalsButtonDelete": "Löschen",
    "goalsButtonComplete": "Als abgeschlossen markieren",
    "goalsProgressLabel": "Fortschritt",
    "goalsDeadlineLabel": "Frist",
    "goalsCategoryRecruitment": "Rekrutierung",
    "goalsCategoryTeamGrowth": "Teamwachstum",
    "goalsCategoryPersonalDevelopment": "Persönliche Entwicklung",
    "goalsCategoryOther": "Sonstiges",
    "createGoalTitle": "Ziel erstellen",
    "createGoalLabelTitle": "Zieltitel",
    "createGoalLabelDescription": "Beschreibung",
    "createGoalLabelCategory": "Kategorie",
    "createGoalLabelTarget": "Zielwert",
    "createGoalLabelDeadline": "Frist",
    "createGoalButtonCreate": "Ziel erstellen",
    "createGoalButtonCancel": "Abbrechen",
    "createGoalSuccess": "Ziel erfolgreich erstellt!",
    "createGoalError": "Fehler beim Erstellen des Ziels. Bitte versuchen Sie es erneut.",
    "leaderboardTitle": "Bestenliste",
    "leaderboardFilterTeamSize": "Teamgröße",
    "leaderboardFilterGrowthRate": "Wachstumsrate",
    "leaderboardFilterRecruitment": "Rekrutierung",
    "leaderboardTimeframeWeek": "Diese Woche",
    "leaderboardTimeframeMonth": "Diesen Monat",
    "leaderboardTimeframeYear": "Dieses Jahr",
    "leaderboardTimeframeAllTime": "Alle Zeiten",
    "leaderboardRankLabel": "Rang",
    "leaderboardYourRank": "Ihr Rang: #{rank}",
    "leaderboardEmptyState": "Keine Daten verfügbar",
    "achievementsTitle": "Erfolge",
    "achievementsUnlockedHeading": "Freigeschaltet",
    "achievementsLockedHeading": "Gesperrt",
    "achievementsProgressLabel": "Fortschritt: {percent}%",
    "achievementsEmptyState": "Noch keine Erfolge freigeschaltet",
    "achievementsCategoryMilestones": "Meilensteine",
    "achievementsCategoryRecruitment": "Rekrutierung",
    "achievementsCategoryEngagement": "Engagement",
    "achievementsCategoryLeadership": "Führung",
    "achievementsShareButton": "Erfolg teilen",
    "referralProgramTitle": "Empfehlungsprogramm",
    "referralProgramYourCode": "Ihr Code",
    "referralProgramYourLink": "Ihr Link",
    "referralProgramButtonCopy": "Kopieren",
    "referralProgramButtonShare": "Teilen",
    "referralProgramStatsHeading": "Empfehlungsstatistiken",
    "referralProgramStatTotalReferrals": "Gesamte Empfehlungen",
    "referralProgramStatActiveReferrals": "Aktive Empfehlungen",
    "referralProgramStatConversionRate": "Konversionsrate",
    "referralProgramRecentHeading": "Kürzliche Empfehlungen",
    "referralProgramEmptyState": "Noch keine Empfehlungen",
    "supportTitle": "Support",
    "supportFaqHeading": "Häufig gestellte Fragen",
    "supportContactHeading": "Kontaktieren Sie uns",
    "supportButtonEmail": "E-Mail-Support",
    "supportButtonChat": "Live-Chat",
    "supportButtonPhone": "Telefon-Support",
    "supportTicketsHeading": "Ihre Tickets",
    "supportEmptyState": "Keine offenen Tickets",
    "supportCreateTicket": "Neues Ticket erstellen",
    "supportTicketStatusOpen": "Offen",
    "supportTicketStatusInProgress": "In Bearbeitung",
    "supportTicketStatusResolved": "Gelöst",
    "supportTicketStatusClosed": "Geschlossen",
    "createSupportTicketTitle": "Support-Ticket erstellen",
    "createSupportTicketLabelSubject": "Betreff",
    "createSupportTicketLabelCategory": "Kategorie",
    "createSupportTicketLabelPriority": "Priorität",
    "createSupportTicketLabelDescription": "Beschreibung",
    "createSupportTicketButtonSubmit": "Ticket einreichen",
    "createSupportTicketButtonCancel": "Abbrechen",
    "createSupportTicketSuccess": "Ticket erfolgreich erstellt!",
    "createSupportTicketError": "Fehler beim Erstellen des Tickets. Bitte versuchen Sie es erneut.",
    "subscriptionTitle": "Abonnement",
    "subscriptionCurrentPlanHeading": "Aktueller Plan",
    "subscriptionPlanFree": "Kostenlos",
    "subscriptionPlanBasic": "Basis",
    "subscriptionPlanPro": "Pro",
    "subscriptionPlanEnterprise": "Unternehmen",
    "subscriptionStatusActive": "Aktiv",
    "subscriptionStatusExpired": "Abgelaufen",
    "subscriptionStatusCancelled": "Gekündigt",
    "subscriptionRenewalDate": "Verlängerungsdatum: {date}",
    "subscriptionButtonUpgrade": "Upgrade",
    "subscriptionButtonDowngrade": "Downgrade",
    "subscriptionButtonCancel": "Abonnement kündigen",
    "subscriptionButtonReactivate": "Reaktivieren",
    "subscriptionFeaturesHeading": "Funktionen",
    "subscriptionBillingHeading": "Abrechnung",
    "subscriptionPaymentMethod": "Zahlungsmethode",
    "subscriptionButtonUpdatePayment": "Zahlungsmethode aktualisieren",
    "subscriptionBillingHistory": "Abrechnungsverlauf",
    "subscriptionInvoiceDate": "Datum",
    "subscriptionInvoiceAmount": "Betrag",
    "subscriptionInvoiceStatus": "Status",
    "subscriptionInvoiceDownload": "Herunterladen",
    "billingTitle": "Abrechnung",
    "billingPaymentMethodHeading": "Zahlungsmethode",
    "billingAddPaymentMethod": "Zahlungsmethode hinzufügen",
    "billingUpdatePaymentMethod": "Zahlungsmethode aktualisieren",
    "billingRemovePaymentMethod": "Entfernen",
    "billingInvoicesHeading": "Rechnungen",
    "billingEmptyState": "Keine Rechnungen verfügbar",
    "billingDownloadInvoice": "Rechnung herunterladen",
    "billingInvoicePaid": "Bezahlt",
    "billingInvoicePending": "Ausstehend",
    "billingInvoiceOverdue": "Überfällig",
    "privacyPolicyTitle": "Datenschutzerklärung",
    "privacyPolicyLastUpdated": "Zuletzt aktualisiert: {date}",
    "privacyPolicyAccept": "Ich akzeptiere die Datenschutzerklärung",
    "termsOfServiceTitle": "Nutzungsbedingungen",
    "termsOfServiceLastUpdated": "Zuletzt aktualisiert: {date}",
    "termsOfServiceAccept": "Ich akzeptiere die Nutzungsbedingungen",
    "onboardingWelcomeTitle": "Willkommen bei Team Build Pro",
    "onboardingWelcomeDescription": "Bauen Sie Ihr professionelles Team mit unserer leistungsstarken Plattform auf.",
    "onboardingButtonNext": "Weiter",
    "onboardingButtonSkip": "Überspringen",
    "onboardingButtonGetStarted": "Loslegen",
    "onboardingStep1Title": "Bauen Sie Ihr Team auf",
    "onboardingStep1Description": "Laden Sie Mitglieder ein und verfolgen Sie Ihr Teamwachstum in Echtzeit.",
    "onboardingStep2Title": "Verfolgen Sie Ihren Fortschritt",
    "onboardingStep2Description": "Überwachen Sie Ihre Leistung mit detaillierten Analysen und Einblicken.",
    "onboardingStep3Title": "Erreichen Sie Ihre Ziele",
    "onboardingStep3Description": "Setzen Sie Ziele und erreichen Sie Meilensteine mit unseren Tools.",
    "onboardingCompleteTitle": "Sie sind startklar!",
    "onboardingCompleteDescription": "Beginnen Sie noch heute mit dem Aufbau Ihres Teams.",
    "searchTitle": "Suchen",
    "searchHint": "Nach allem suchen...",
    "searchEmptyState": "Keine Ergebnisse gefunden",
    "searchRecentHeading": "Kürzliche Suchen",
    "searchClearRecent": "Verlauf löschen",
    "searchFilterAll": "Alle",
    "searchFilterMembers": "Mitglieder",
    "searchFilterMessages": "Nachrichten",
    "searchFilterResources": "Ressourcen",
    "searchFilterEvents": "Veranstaltungen",
    "calendarTitle": "Kalender",
    "calendarViewMonth": "Monat",
    "calendarViewWeek": "Woche",
    "calendarViewDay": "Tag",
    "calendarToday": "Heute",
    "calendarNoEvents": "Keine Veranstaltungen",
    "calendarAddEvent": "Veranstaltung hinzufügen",
    "notificationSettingsTitle": "Benachrichtigungseinstellungen",
    "notificationSettingsPushHeading": "Push-Benachrichtigungen",
    "notificationSettingsEmailHeading": "E-Mail-Benachrichtigungen",
    "notificationSettingsSmsHeading": "SMS-Benachrichtigungen",
    "notificationSettingsToggleNewMembers": "Neue Teammitglieder",
    "notificationSettingsToggleMilestones": "Meilensteine erreicht",
    "notificationSettingsToggleMessages": "Neue Nachrichten",
    "notificationSettingsToggleEvents": "Bevorstehende Veranstaltungen",
    "notificationSettingsToggleUpdates": "App-Updates",
    "notificationSettingsTogglePromotions": "Werbeaktionen",
    "notificationSettingsSaveButton": "Einstellungen speichern",
    "notificationSettingsSaveSuccess": "Einstellungen gespeichert!",
    "notificationSettingsSaveError": "Fehler beim Speichern der Einstellungen.",
    "languageSettingsTitle": "Spracheinstellungen",
    "languageSettingsCurrentLanguage": "Aktuelle Sprache",
    "languageSettingsSelectLanguage": "Sprache auswählen",
    "languageEnglish": "Englisch",
    "languageSpanish": "Spanisch",
    "languageFrench": "Französisch",
    "languageGerman": "Deutsch",
    "languageItalian": "Italienisch",
    "languagePortuguese": "Portugiesisch",
    "languageChinese": "Chinesisch",
    "languageJapanese": "Japanisch",
    "languageKorean": "Koreanisch",
    "languageRussian": "Russisch",
    "themeSettingsTitle": "Design-Einstellungen",
    "themeSettingsCurrentTheme": "Aktuelles Design",
    "themeLight": "Hell",
    "themeDark": "Dunkel",
    "themeSystem": "System-Standard",
    "accessibilitySettingsTitle": "Barrierefreiheit",
    "accessibilityFontSizeLabel": "Schriftgröße",
    "accessibilityFontSizeSmall": "Klein",
    "accessibilityFontSizeMedium": "Mittel",
    "accessibilityFontSizeLarge": "Groß",
    "accessibilityFontSizeExtraLarge": "Extra Groß",
    "accessibilityHighContrastLabel": "Hoher Kontrast",
    "accessibilityScreenReaderLabel": "Bildschirmleser-Unterstützung",
    "accessibilityReduceMotionLabel": "Bewegung reduzieren",
    "securitySettingsTitle": "Sicherheitseinstellungen",
    "securityChangePasswordButton": "Passwort ändern",
    "securityTwoFactorHeading": "Zwei-Faktor-Authentifizierung",
    "securityTwoFactorEnabled": "Aktiviert",
    "securityTwoFactorDisabled": "Deaktiviert",
    "securityTwoFactorEnableButton": "Aktivieren",
    "securityTwoFactorDisableButton": "Deaktivieren",
    "securityBiometricHeading": "Biometrische Authentifizierung",
    "securityBiometricEnabled": "Aktiviert",
    "securityBiometricDisabled": "Deaktiviert",
    "securityBiometricEnableButton": "Aktivieren",
    "securityBiometricDisableButton": "Deaktivieren",
    "securitySessionsHeading": "Aktive Sitzungen",
    "securitySessionCurrent": "Aktuelle Sitzung",
    "securitySessionDevice": "Gerät: {device}",
    "securitySessionLocation": "Standort: {location}",
    "securitySessionLastActive": "Zuletzt aktiv: {time}",
    "securitySessionRevokeButton": "Widerrufen",
    "securitySessionRevokeAllButton": "Alle anderen Sitzungen widerrufen",
    "changePasswordTitle": "Passwort ändern",
    "changePasswordLabelCurrent": "Aktuelles Passwort",
    "changePasswordLabelNew": "Neues Passwort",
    "changePasswordLabelConfirm": "Neues Passwort bestätigen",
    "changePasswordButtonSave": "Passwort ändern",
    "changePasswordButtonCancel": "Abbrechen",
    "changePasswordSuccess": "Passwort erfolgreich geändert!",
    "changePasswordError": "Fehler beim Ändern des Passworts. Bitte versuchen Sie es erneut.",
    "changePasswordMismatch": "Passwörter stimmen nicht überein",
    "changePasswordTooWeak": "Passwort ist zu schwach. Verwenden Sie mindestens 8 Zeichen.",
    "changePasswordTodoMessage": "Hier muss das Formular zum Ändern des Passworts implementiert werden.",
    "twoFactorSetupTitle": "Zwei-Faktor-Authentifizierung einrichten",
    "twoFactorSetupStep1": "Schritt 1: Authenticator-App herunterladen",
    "twoFactorSetupStep1Description": "Laden Sie eine Authenticator-App wie Google Authenticator oder Authy herunter.",
    "twoFactorSetupStep2": "Schritt 2: QR-Code scannen",
    "twoFactorSetupStep2Description": "Scannen Sie diesen QR-Code mit Ihrer Authenticator-App.",
    "twoFactorSetupStep3": "Schritt 3: Code eingeben",
    "twoFactorSetupStep3Description": "Geben Sie den 6-stelligen Code aus Ihrer Authenticator-App ein.",
    "twoFactorSetupCodeLabel": "Verifizierungscode",
    "twoFactorSetupButtonVerify": "Verifizieren und Aktivieren",
    "twoFactorSetupButtonCancel": "Abbrechen",
    "twoFactorSetupSuccess": "Zwei-Faktor-Authentifizierung aktiviert!",
    "twoFactorSetupError": "Ungültiger Code. Bitte versuchen Sie es erneut.",
    "twoFactorDisableTitle": "Zwei-Faktor-Authentifizierung deaktivieren",
    "twoFactorDisableWarning": "Dies macht Ihr Konto weniger sicher. Sind Sie sicher?",
    "twoFactorDisableCodeLabel": "Geben Sie Ihren aktuellen Code ein",
    "twoFactorDisableButtonConfirm": "Deaktivieren",
    "twoFactorDisableButtonCancel": "Abbrechen",
    "twoFactorDisableSuccess": "Zwei-Faktor-Authentifizierung deaktiviert",
    "twoFactorDisableError": "Fehler beim Deaktivieren. Bitte versuchen Sie es erneut.",
    "dataPrivacyTitle": "Datenschutz",
    "dataPrivacyDownloadHeading": "Ihre Daten herunterladen",
    "dataPrivacyDownloadDescription": "Fordern Sie eine Kopie Ihrer Daten an.",
    "dataPrivacyDownloadButton": "Daten anfordern",
    "dataPrivacyDownloadSuccess": "Datenanfrage eingereicht. Sie erhalten eine E-Mail, wenn Ihre Daten fertig sind.",
    "dataPrivacyDownloadError": "Fehler bei der Anfrage. Bitte versuchen Sie es erneut.",
    "dataPrivacyDeleteHeading": "Konto löschen",
    "dataPrivacyDeleteDescription": "Löschen Sie Ihr Konto und alle zugehörigen Daten dauerhaft.",
    "dataPrivacyDeleteButton": "Konto löschen",
    "errorTitle": "Fehler",
    "errorGeneric": "Es ist ein Fehler aufgetreten. Bitte versuchen Sie es erneut.",
    "errorNetwork": "Netzwerkfehler. Bitte überprüfen Sie Ihre Verbindung.",
    "errorTimeout": "Anfrage hat zu lange gedauert. Bitte versuchen Sie es erneut.",
    "errorUnauthorized": "Nicht autorisiert. Bitte melden Sie sich erneut an.",
    "errorForbidden": "Sie haben keine Berechtigung für diese Aktion.",
    "errorNotFound": "Angeforderte Ressource nicht gefunden.",
    "errorServerError": "Serverfehler. Bitte versuchen Sie es später erneut.",
    "errorButtonRetry": "Erneut versuchen",
    "errorButtonGoBack": "Zurück",
    "errorButtonGoHome": "Zur Startseite",
    "loadingTitle": "Lädt...",
    "loadingPleaseWait": "Bitte warten...",
    "successTitle": "Erfolg",
    "successGeneric": "Vorgang erfolgreich abgeschlossen!",
    "warningTitle": "Warnung",
    "infoTitle": "Information",
    "confirmTitle": "Bestätigen",
    "confirmButtonYes": "Ja",
    "confirmButtonNo": "Nein",
    "confirmButtonOk": "OK",
    "confirmButtonCancel": "Abbrechen",
    "dialogButtonClose": "Schließen",
    "dialogButtonSave": "Speichern",
    "dialogButtonDelete": "Löschen",
    "dialogButtonEdit": "Bearbeiten",
    "dialogButtonCreate": "Erstellen",
    "dialogButtonUpdate": "Aktualisieren",
    "dialogButtonSubmit": "Absenden",
    "validationRequired": "Dieses Feld ist erforderlich",
    "validationEmail": "Bitte geben Sie eine gültige E-Mail-Adresse ein",
    "validationPhone": "Bitte geben Sie eine gültige Telefonnummer ein",
    "validationMinLength": "Muss mindestens {min} Zeichen lang sein",
    "validationMaxLength": "Darf maximal {max} Zeichen lang sein",
    "validationMinValue": "Muss mindestens {min} sein",
    "validationMaxValue": "Darf maximal {max} sein",
    "validationPasswordMatch": "Passwörter müssen übereinstimmen",
    "validationUrl": "Bitte geben Sie eine gültige URL ein",
    "validationDate": "Bitte geben Sie ein gültiges Datum ein",
    "validationTime": "Bitte geben Sie eine gültige Uhrzeit ein",
    "filterTitle": "Filtern",
    "filterApply": "Filter anwenden",
    "filterClear": "Filter löschen",
    "filterReset": "Zurücksetzen",
    "sortTitle": "Sortieren",
    "sortAscending": "Aufsteigend",
    "sortDescending": "Absteigend",
    "paginationFirst": "Erste",
    "paginationPrevious": "Vorherige",
    "paginationNext": "Nächste",
    "paginationLast": "Letzte",
    "paginationPage": "Seite {page} von {total}",
    "paginationItemsPerPage": "Elemente pro Seite",
    "emptyStateTitle": "Noch nichts hier",
    "emptyStateDescription": "Beginnen Sie, indem Sie Ihre erste Aktion erstellen.",
    "emptyStateButton": "Loslegen",
    "noDataAvailable": "Keine Daten verfügbar",
    "comingSoon": "Demnächst verfügbar",
    "underConstruction": "Diese Funktion ist noch in Arbeit",
    "maintenanceMode": "Wartungsmodus",
    "maintenanceMessage": "Wir führen gerade eine geplante Wartung durch. Bitte versuchen Sie es später erneut.",
    "offlineMode": "Offline-Modus",
    "offlineMessage": "Sie sind offline. Einige Funktionen sind möglicherweise nicht verfügbar.",
    "syncInProgress": "Wird synchronisiert...",
    "syncComplete": "Synchronisierung abgeschlossen",
    "syncFailed": "Synchronisierung fehlgeschlagen",
    "lastSyncLabel": "Zuletzt synchronisiert: {time}",
    "refreshButton": "Aktualisieren",
    "shareButton": "Teilen",
    "copyButton": "Kopieren",
    "pasteButton": "Einfügen",
    "cutButton": "Ausschneiden",
    "undoButton": "Rückgängig",
    "redoButton": "Wiederholen",
    "selectAllButton": "Alles auswählen",
    "deselectAllButton": "Auswahl aufheben",
    "expandButton": "Erweitern",
    "collapseButton": "Reduzieren",
    "moreButton": "Mehr",
    "lessButton": "Weniger",
    "showMoreButton": "Mehr anzeigen",
    "showLessButton": "Weniger anzeigen",
    "viewAllButton": "Alle anzeigen",
    "viewDetailsButton": "Details anzeigen",
    "previewButton": "Vorschau",
    "downloadButton": "Herunterladen",
    "uploadButton": "Hochladen",
    "printButton": "Drucken",
    "exportButton": "Exportieren",
    "importButton": "Importieren",
    "addButton": "Hinzufügen",
    "removeButton": "Entfernen",
    "clearButton": "Löschen",
    "resetButton": "Zurücksetzen",
    "applyButton": "Anwenden",
    "doneButton": "Fertig",
    "finishButton": "Abschließen",
    "backButton": "Zurück",
    "nextButton": "Weiter",
    "previousButton": "Vorherige",
    "skipButton": "Überspringen",
    "continueButton": "Fortfahren",
    "proceedButton": "Fortfahren",
    "closeButton": "Schließen",
    "dismissButton": "Verwerfen",
    "learnMoreButton": "Mehr erfahren",
    "readMoreButton": "Mehr lesen",
    "helpButton": "Hilfe",
    "feedbackButton": "Feedback",
    "reportBugButton": "Fehler melden",
    "contactSupportButton": "Support kontaktieren",
    "rateAppButton": "App bewerten",
    "menuButton": "Menü",
    "settingsButton": "Einstellungen",
    "profileButton": "Profil",
    "logoutButton": "Abmelden",
    "loginButton": "Anmelden",
    "signupButton": "Registrieren",
    "todayLabel": "Heute",
    "yesterdayLabel": "Gestern",
    "tomorrowLabel": "Morgen",
    "thisWeekLabel": "Diese Woche",
    "lastWeekLabel": "Letzte Woche",
    "nextWeekLabel": "Nächste Woche",
    "thisMonthLabel": "Diesen Monat",
    "lastMonthLabel": "Letzten Monat",
    "nextMonthLabel": "Nächsten Monat",
    "thisYearLabel": "Dieses Jahr",
    "lastYearLabel": "Letztes Jahr",
    "nextYearLabel": "Nächstes Jahr",
    "neverLabel": "Nie",
    "alwaysLabel": "Immer",
    "yesLabel": "Ja",
    "noLabel": "Nein",
    "onLabel": "Ein",
    "offLabel": "Aus",
    "enabledLabel": "Aktiviert",
    "disabledLabel": "Deaktiviert",
    "activeLabel": "Aktiv",
    "inactiveLabel": "Inaktiv",
    "publicLabel": "Öffentlich",
    "privateLabel": "Privat",
    "draftLabel": "Entwurf",
    "publishedLabel": "Veröffentlicht",
    "archivedLabel": "Archiviert",
    "deletedLabel": "Gelöscht",
    "newLabel": "Neu",
    "updatedLabel": "Aktualisiert",
    "savedLabel": "Gespeichert",
    "pendingLabel": "Ausstehend",
    "approvedLabel": "Genehmigt",
    "rejectedLabel": "Abgelehnt",
    "completedLabel": "Abgeschlossen",
    "cancelledLabel": "Abgebrochen",
    "failedLabel": "Fehlgeschlagen",
    "successLabel": "Erfolg",
    "errorLabel": "Fehler",
    "warningLabel": "Warnung",
    "infoLabel": "Information",
    "requiredLabel": "Erforderlich",
    "optionalLabel": "Optional",
    "defaultLabel": "Standard",
    "customLabel": "Benutzerdefiniert",
    "allLabel": "Alle",
    "noneLabel": "Keine",
    "otherLabel": "Sonstiges",
    "unknownLabel": "Unbekannt",
    "naLabel": "N/A",
    "tbaLabel": "Wird bekannt gegeben",
    "phoneNumberHint": "Telefonnummer",
    "emailAddressHint": "E-Mail-Adresse",
    "passwordHint": "Passwort",
    "confirmPasswordHint": "Passwort bestätigen",
    "searchHintGeneric": "Suchen...",
    "namePlaceholder": "Name",
    "titlePlaceholder": "Titel",
    "descriptionPlaceholder": "Beschreibung",
    "messagePlaceholder": "Nachricht",
    "commentPlaceholder": "Kommentar",
    "notePlaceholder": "Notiz",
    "urlPlaceholder": "URL",
    "datePlaceholder": "Datum",
    "timePlaceholder": "Uhrzeit",
    "locationPlaceholder": "Standort",
    "addressPlaceholder": "Adresse",
    "cityPlaceholder": "Stadt",
    "statePlaceholder": "Bundesland",
    "countryPlaceholder": "Land",
    "zipCodePlaceholder": "Postleitzahl",
    "companyPlaceholder": "Unternehmen",
    "websitePlaceholder": "Website",
    "selectOption": "Option auswählen",
    "selectDate": "Datum auswählen",
    "selectTime": "Uhrzeit auswählen",
    "selectFile": "Datei auswählen",
    "selectImage": "Bild auswählen",
    "selectCountry": "Land auswählen",
    "selectLanguage": "Sprache auswählen",
    "selectCurrency": "Währung auswählen",
    "selectTimezone": "Zeitzone auswählen",
    "dragDropFiles": "Dateien hierher ziehen oder klicken zum Hochladen",
    "maxFileSize": "Maximale Dateigröße: {size}",
    "allowedFileTypes": "Erlaubte Dateitypen: {types}",
    "fileUploadSuccess": "Datei erfolgreich hochgeladen",
    "fileUploadError": "Fehler beim Hochladen der Datei",
    "imageUploadSuccess": "Bild erfolgreich hochgeladen",
    "imageUploadError": "Fehler beim Hochladen des Bildes",
    "deleteConfirmTitle": "Löschen bestätigen",
    "deleteConfirmMessage": "Sind Sie sicher, dass Sie dies löschen möchten? Diese Aktion kann nicht rückgängig gemacht werden.",
    "deleteConfirmButton": "Ja, löschen",
    "deleteCancelButton": "Abbrechen",
    "saveChangesPrompt": "Möchten Sie Ihre Änderungen speichern?",
    "discardChangesPrompt": "Nicht gespeicherte Änderungen verwerfen?",
    "unsavedChangesWarning": "Sie haben nicht gespeicherte Änderungen. Sind Sie sicher, dass Sie die Seite verlassen möchten?",
    "copiedToClipboard": "In die Zwischenablage kopiert",
    "copyToClipboardFailed": "Fehler beim Kopieren in die Zwischenablage",
    "linkCopied": "Link kopiert",
    "textCopied": "Text kopiert",
    "codeCopied": "Code kopiert",
    "timeAgoSeconds": "vor {seconds} Sekunden",
    "timeAgoMinute": "vor 1 Minute",
    "timeAgoMinutes": "vor {minutes} Minuten",
    "timeAgoHour": "vor 1 Stunde",
    "timeAgoHours": "vor {hours} Stunden",
    "timeAgoDay": "vor 1 Tag",
    "timeAgoDays": "vor {days} Tagen",
    "timeAgoWeek": "vor 1 Woche",
    "timeAgoWeeks": "vor {weeks} Wochen",
    "timeAgoMonth": "vor 1 Monat",
    "timeAgoMonths": "vor {months} Monaten",
    "timeAgoYear": "vor 1 Jahr",
    "timeAgoYears": "vor {years} Jahren",
    "justNow": "Gerade eben",
    "online": "Online",
    "offline": "Offline",
    "away": "Abwesend",
    "busy": "Beschäftigt",
    "invisible": "Unsichtbar",
    "lastSeenLabel": "Zuletzt gesehen: {time}",
    "typingIndicatorSingle": "{name} schreibt...",
    "typingIndicatorMultiple": "{count} Personen schreiben...",
    "memberSingular": "Mitglied",
    "memberPlural": "Mitglieder",
    "itemSingular": "Element",
    "itemPlural": "Elemente",
    "resultSingular": "Ergebnis",
    "resultPlural": "Ergebnisse",
    "messageSingular": "Nachricht",
    "messagePlural": "Nachrichten",
    "notificationSingular": "Benachrichtigung",
    "notificationPlural": "Benachrichtigungen",
    "eventSingular": "Veranstaltung",
    "eventPlural": "Veranstaltungen",
    "goalSingular": "Ziel",
    "goalPlural": "Ziele",
    "achievementSingular": "Erfolg",
    "achievementPlural": "Erfolge",
    "daySingular": "Tag",
    "dayPlural": "Tage",
    "weekSingular": "Woche",
    "weekPlural": "Wochen",
    "monthSingular": "Monat",
    "monthPlural": "Monate",
    "yearSingular": "Jahr",
    "yearPlural": "Jahre",
    "hourSingular": "Stunde",
    "hourPlural": "Stunden",
    "minuteSingular": "Minute",
    "minutePlural": "Minuten",
    "secondSingular": "Sekunde",
    "secondPlural": "Sekunden",
    "percentSymbol": "%",
    "currencySymbol": "€",
    "andConjunction": "und",
    "orConjunction": "oder",
    "ofPreposition": "von"
}

# Load existing files
with open('/Users/sscott/tbp/lib/l10n/app_en.arb', 'r', encoding='utf-8') as f:
    en_data = json.load(f)

with open('/Users/sscott/tbp/lib/l10n/app_de.arb', 'r', encoding='utf-8') as f:
    de_data = json.load(f)

# Update German file with translations
updated_count = 0
for key, translation in translations.items():
    if key in en_data:
        de_data[key] = translation
        updated_count += 1
        # Also copy metadata if it exists
        metadata_key = f'@{key}'
        if metadata_key in en_data:
            de_data[metadata_key] = en_data[metadata_key]

# Write updated German file
with open('/Users/sscott/tbp/lib/l10n/app_de.arb', 'w', encoding='utf-8') as f:
    json.dump(de_data, f, ensure_ascii=False, indent=2)

print(f'Successfully updated {updated_count} translations')
print(f'Total keys in German file: {len([k for k in de_data.keys() if not k.startswith("@")])}')
