/**
 * Demo Intake Configuration Template
 *
 * This file is generated by the demo-generator-functions.js
 * and contains firm-specific settings for the intake demo.
 *
 * TOKENS:
 * {{FIRM_NAME}} - Firm name from analysis
 * {{PROXY_URL}} - Claude API proxy URL (constant)
 * {{MODEL}} - Claude model to use
 * {{WEBHOOK_URL}} - Optional webhook for lead delivery
 * {{LEAD_ID}} - Firestore lead document ID
 * {{STATE}} - Firm's state/jurisdiction
 */

window.DEMO_INTAKE_CONFIG = {
    // =========================================================================
    // FIRM IDENTITY
    // =========================================================================
    firmName: '{{FIRM_NAME}}',
    firmPhone: '{{FIRM_PHONE}}',
    firmWebsite: '{{FIRM_WEBSITE}}',
    firmLogo: {{FIRM_LOGO}},

    // =========================================================================
    // BRANDING
    // =========================================================================
    primaryColor: '{{PRIMARY_DARK}}',
    secondaryColor: '{{PRIMARY_BLUE}}',
    accentColor: '{{ACCENT_COLOR}}',
    accentColorLight: '{{ACCENT_COLOR_LIGHT}}',

    // =========================================================================
    // API CONFIGURATION
    // =========================================================================
    proxyUrl: '{{PROXY_URL}}',
    model: '{{MODEL}}',
    maxTokens: 4096,

    // =========================================================================
    // WEBHOOK CONFIGURATION
    // =========================================================================
    webhookUrl: {{WEBHOOK_URL}},
    webhookKey: {{WEBHOOK_KEY}},
    webhookFilter: 'qualified',

    // =========================================================================
    // SCHEDULING
    // =========================================================================
    scheduleUrl: {{SCHEDULE_URL}},
    scheduleButtonText: 'Schedule Your Free Consultation',

    // =========================================================================
    // PRACTICE AREA CONFIGURATION
    // =========================================================================
    primaryPracticeArea: '{{PRIMARY_PRACTICE_AREA}}',
    practiceAreas: {{PRACTICE_AREAS_JSON}},

    // =========================================================================
    // JURISDICTION
    // =========================================================================
    state: '{{STATE}}',

    // =========================================================================
    // DEMO METADATA
    // =========================================================================
    leadId: '{{LEAD_ID}}',
    generatedAt: '{{GENERATED_AT}}',
    version: '1.0.0'
};

// Configuration validation
(function validateConfig() {
    const config = window.DEMO_INTAKE_CONFIG;
    const warnings = [];

    if (!config.proxyUrl || config.proxyUrl.includes('{{')) {
        warnings.push('proxyUrl is not configured - API calls will fail');
    }

    if (!config.firmName || config.firmName.includes('{{')) {
        warnings.push('firmName is using default value');
    }

    if (warnings.length > 0) {
        console.warn('[Demo Intake Config] Configuration warnings:');
        warnings.forEach(w => console.warn('  - ' + w));
    }
})();
