# Uncomment this line to define a global platform for your project
platform :osx, '10.15'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
# Disable this by uncommenting the next line.
# ENV['COCOAPODS_DISABLE_STATS'] = 'true'

# Add your pods here
target 'Runner' do
  use_frameworks!
  use_modular_headers!

  # Pods for Runner
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Functions'
  pod 'Firebase/Firestore'
  pod 'Firebase/Analytics'
  pod 'app_links', :git => 'https://github.com/flutter/plugins.git', :branch => 'main'
end
